### ISSUE TITLE
Update README to give better instructions for defining stream schemas

### ISSUE THREAD

**Issue by chipmaurer** [pravega/presto-connector#39] opened 2021-06-09 12:57 UTC
The README needs some additional content to document how to create a schema definition for reading stream data, whether by JSON files, or by using Schema Registry.

**Comment by adrdc** [comment] 2021-06-09 14:00
looks like a duplicate of https://github.com/pravega/presto-connector/issues/29

**Closed by adrdc** 2021-06-09 14:00 UTC
